version: '3.3'

services:
  medbook-next:
    container_name: medbook-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000
    
    volumes:
      - ./:/usr/src/medbook-next
    working_dir: /usr/src/medbook-next

    networks: 
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge



# medbook-next:    localhost:4000 <=> container:3000
# medbook-api:     localhost:4001 <=> container:3004
# medbook-batc     localhost:4002 <=> container:3005